In [17]:
import pandas as pd

## load data

In [ ]:
df = pd.read_csv('/Users/connorhall/datasets/inst414/module 3 assignment/Public.csv', usecols=['SPECIES', 'AIRPORT'])
df = df.dropna()
# remove unknown species
df = df[(~df['SPECIES'].str.contains('unknown|perching birds', case=False)) &
        (~df['AIRPORT'].str.contains('unknown', case=False))]
# species must have >= 10 collisions
df = df[df.groupby('SPECIES')['SPECIES'].transform('count') >= 10]
df

                                    AIRPORT                SPECIES
8       NORMAN Y. MINETA SAN JOSE INTL ARPT         American robin
11                          ALEXANDRIA INTL             Blackbirds
13                    SYRACUSE HANCOCK INTL                  Gulls
14                      OAKLAND COUNTY INTL          Mourning dove
15                         LOS ANGELES INTL       American kestrel
...                                     ...                    ...
339266                  EVANSVILLE REGIONAL          Chimney swift
339267                  SEATTLE-TACOMA INTL          Cedar waxwing
339268             CHICAGO O'HARE INTL ARPT  Yellow-rumped warbler
339269     ROANOKE REGNL ARPT/WOODRUM FIELD      European starling
339271                      LA GUARDIA ARPT           Song sparrow

[181345 rows x 2 columns]

## calculate collision counts

In [19]:
collision_count = pd.crosstab(df['SPECIES'], df['AIRPORT']).stack('AIRPORT')
collision_count

SPECIES             AIRPORT
Acadian flycatcher  ABBEVILLE CHRIS CRUSTA MEMORIAL APRT    0
                    ABERDEEN REGIONAL ARPT                  0
                    ABERNATHY FIELD ARPT                    0
                    ABILENE REGIONAL ARPT                   0
                    ABRAHAM LINCOLN CAPITAL ARPT            0
                                                           ..
Zenaida dove        ZAMPERINI FIELD ARPT                    0
                    ZANESVILLE MUNICIPAL ARPT               0
                    ZELIENOPLE MUNICIPAL                    0
                    ZEPHYRHILLS MUNICIPAL ARPT              0
                    ZURICH                                  0
Length: 1020528, dtype: int64

### separate airport and species index

In [20]:
species = collision_count.index.get_level_values('SPECIES').tolist()
airports = collision_count.index.get_level_values('AIRPORT').tolist()

collisions_df = pd.DataFrame({'Species': species, 'Airport': airports})
collisions_df['Count'] = collision_count.values
collisions_df

                    Species                               Airport  Count
0        Acadian flycatcher  ABBEVILLE CHRIS CRUSTA MEMORIAL APRT      0
1        Acadian flycatcher                ABERDEEN REGIONAL ARPT      0
2        Acadian flycatcher                  ABERNATHY FIELD ARPT      0
3        Acadian flycatcher                 ABILENE REGIONAL ARPT      0
4        Acadian flycatcher          ABRAHAM LINCOLN CAPITAL ARPT      0
...                     ...                                   ...    ...
1020523        Zenaida dove                  ZAMPERINI FIELD ARPT      0
1020524        Zenaida dove             ZANESVILLE MUNICIPAL ARPT      0
1020525        Zenaida dove                  ZELIENOPLE MUNICIPAL      0
1020526        Zenaida dove            ZEPHYRHILLS MUNICIPAL ARPT      0
1020527        Zenaida dove                                ZURICH      0

[1020528 rows x 3 columns]

### add collision counts to new dataframe format

In [21]:
# create lists of unique species names and airport names
unique_sp = sorted(list(set(species)))
unique_air = sorted(list(set(airports)))

# create list of collision count lists
counts = []
for sp in unique_sp:
    sp_filter = collisions_df[collisions_df['Species'] == sp]
    counts.append(sp_filter['Count'].tolist())
    
# create new dataframe format
collisions_df = pd.DataFrame(counts, columns=unique_air, index=unique_sp)
pd.options.display.max_columns = None
collisions_df

                                 ABBEVILLE CHRIS CRUSTA MEMORIAL APRT  \
Acadian flycatcher                                                  0
Alder flycatcher                                                    0
Alder/willow flycatcher complex                                     0
American alligator                                                  0
American avocet                                                     0
...                                                               ...
Yellow-headed blackbird                                             0
Yellow-rumped warbler                                               0
Yellow-throated warbler                                             0
Zebra dove                                                          0
Zenaida dove                                                        0

                                 ABERDEEN REGIONAL ARPT  ABERNATHY FIELD ARPT  \
Acadian flycatcher                                    0                     0
Alder flycatcher                                      0                     0
Alder/willow flycatcher complex                       0                     0
American alligator                                    0                     0
American avocet                                       0                     0
...                                                 ...                   ...
Yellow-headed blackbird                               0                     0
Yellow-rumped warbler                                 0                     0
Yellow-throated warbler                               0                     0
Zebra dove                                            0                     0
Zenaida dove                                          0                     0

                                 ABILENE REGIONAL ARPT  \
Acadian flycatcher                                   0
Alder flycatcher                                     0
Alder/willow flycatcher complex                      0
American alligator                                   0
American avocet                                      0
...                                                ...
Yellow-headed blackbird                              0
Yellow-rumped warbler                                0
Yellow-throated warbler                              0
Zebra dove                                           0
Zenaida dove                                         0

                                 ABRAHAM LINCOLN CAPITAL ARPT  \
Acadian flycatcher                                          0
Alder flycatcher                                            0
Alder/willow flycatcher complex                             0
American alligator                                          0
American avocet                                             0
...                                                       ...
Yellow-headed blackbird                                     0
Yellow-rumped warbler                                       0
Yellow-throated warbler                                     0
Zebra dove                                                  0
Zenaida dove                                                0

                                 ABRAMS MUNICIPAL ARPT  \
Acadian flycatcher                                   0
Alder flycatcher                                     0
Alder/willow flycatcher complex                      0
American alligator                                   0
American avocet                                      0
...                                                ...
Yellow-headed blackbird                              0
Yellow-rumped warbler                                0
Yellow-throated warbler                              0
Zebra dove                                           0
Zenaida dove                                         0

                                 ACADIANA REGIONAL ARPT  ADAK ARPT  \
Acadian flycatcher                                    0          0
Alder flycatcher                                      0          0
Alder/willow flycatcher complex                       0          0
American alligator                                    0          0
American avocet                                       0          0
...                                                 ...        ...
Yellow-headed blackbird                               0          0
Yellow-rumped warbler                                 0          0
Yellow-throated warbler                               0          0
Zebra dove                                            0          0
Zenaida dove                                          0          0

                                 ADAMS COUNTY- LEGION FIELD  \
Acadian flycatcher                                        0
Alder flycatcher                                          0
Alder/willow flycatcher complex                           0
American alligator                                        0
American avocet                                           0
...                                                     ...
Yellow-headed blackbird                                   0
Yellow-rumped warbler                                     0
Yellow-throated warbler                                   0
Zebra dove                                                0
Zenaida dove                                              0

                                 ADDINGTON FIELD ARPT  ADDISON AIRPORT  \
Acadian flycatcher                                  0                0
Alder flycatcher                                    0                0
Alder/willow flycatcher complex                     0                0
American alligator                                  0                0
American avocet                                     0                0
...                                               ...              ...
Yellow-headed blackbird                             0                0
Yellow-rumped warbler                               0                0
Yellow-throated warbler                             0                0
Zebra dove                                          0                0
Zenaida dove                                        0                0

                                 ADIRONDACK REGIONAL ARPT  AEROACRES ARPT  \
Acadian flycatcher                                      0               0
Alder flycatcher                                        0               0
Alder/willow flycatcher complex                         0               0
American alligator                                      0               0
American avocet                                         0               0
...                                                   ...             ...
Yellow-headed blackbird                                 0               0
Yellow-rumped warbler                                   0               0
Yellow-throated warbler                                 0               0
Zebra dove                                              0               0
Zenaida dove                                            0               0

                                 AEROFLEX-ANDOVER  AIKEN REGIONAL ARPT  \
Acadian flycatcher                              0                    0
Alder flycatcher                                0                    0
Alder/willow flycatcher complex                 0                    0
American alligator                              0                    0
American avocet                                 0                    0
...                                           ...                  ...
Yellow-headed blackbird                         0                    0
Yellow-rumped warbler                           0                    0
Yellow-throated warbler                         0                    0
Zebra dove                                      0                    0
Zenaida dove                                    0                    0

                                 AIR HAVEN ARPT  AIR LOGICTICS N HELIPORT  \
Acadian flycatcher                            0                         0
Alder flycatcher                              0                         0
Alder/willow flycatcher complex               0                         0
American alligator                            0                         0
American avocet                               0                         0
...                                         ...                       ...
Yellow-headed blackbird                       0                         0
Yellow-rumped warbler                         0                         0
Yellow-throated warbler                       0                         0
Zebra dove                                    0                         0
Zenaida dove                                  0                         0

                                 AIR LOGISTICS HELIPORT  AIRGLADES AIRPORT  \
Acadian flycatcher                                    0                  0
Alder flycatcher                                      0                  0
Alder/willow flycatcher complex                       0                  0
American alligator                                    0                  0
American avocet                                       0                  0
...                                                 ...                ...
Yellow-headed blackbird                               0                  0
Yellow-rumped warbler                                 0                  0
Yellow-throated warbler                               0                  0
Zebra dove                                            0                  0
Zenaida dove                                          0                  0

                                 AIRHAVEN  AIRLAKE ARPT  \
Acadian flycatcher                      0             0
Alder flycatcher                        0             0
Alder/willow flycatcher complex         0             0
American alligator                      0             0
American avocet                         0             0
...                                   ...           ...
Yellow-headed blackbird                 0             0
Yellow-rumped warbler                   0             0
Yellow-throated warbler                 0             0
Zebra dove                              0             0
Zenaida dove                            0             0

                                 AK-CHIN REGIONAL AIRPORT  \
Acadian flycatcher                                      0
Alder flycatcher                                        0
Alder/willow flycatcher complex                         0
American alligator                                      0
American avocet                                         0
...                                                   ...
Yellow-headed blackbird                                 0
Yellow-rumped warbler                                   0
Yellow-throated warbler                                 0
Zebra dove                                              0
Zenaida dove                                            0

                                 AKRON FULTON INTL ARPT  \
Acadian flycatcher                                    0
Alder flycatcher                                      0
Alder/willow flycatcher complex                       0
American alligator                                    0
American avocet                                       0
...                                                 ...
Yellow-headed blackbird                               0
Yellow-rumped warbler                                 0
Yellow-throated warbler                               0
Zebra dove                                            0
Zenaida dove                                          0

                                 AKRON-CANTON REGIONAL  ALBANY INTL  \
Acadian flycatcher                                   0            0
Alder flycatcher                                     0            0
Alder/willow flycatcher complex                      0            0
American alligator                                   0            0
American avocet                                      0            0
...                                                ...          ...
Yellow-headed blackbird                              0            0
Yellow-rumped warbler                                0            0
Yellow-throated warbler                              0            0
Zebra dove                                           0            0
Zenaida dove                                         0            0

                                 ALBERT J ELLIS  ALBERT LEA MUNICIPAL ARPT  \
Acadian flycatcher                            0                          0
Alder flycatcher                              0                          0
Alder/willow flycatcher complex               0                          0
American alligator                            0                          0
American avocet                               0                          0
...                                         ...                        ...
Yellow-headed blackbird                       0                          0
Yellow-rumped warbler                         2                          0
Yellow-throated warbler                       0                          0
Zebra dove                                    0                          0
Zenaida dove                                  0                          0

                                 ALBERT WHITTED  ALBUQUERQUE INTL SUNPORT  \
Acadian flycatcher                            0                         0
Alder flycatcher                              0                         0
Alder/willow flycatcher complex               0                         0
American alligator                            0                         0
American avocet                               0                         0
...                                         ...                       ...
Yellow-headed blackbird                       0                         0
Yellow-rumped warbler                         0                         1
Yellow-throated warbler                       0                         0
Zebra dove                                    0                         0
Zenaida dove                                  0                         0

                                 ALDERNEY ARPT  \
Acadian flycatcher                           0
Alder flycatcher                             0
Alder/willow flycatcher complex              0
American alligator                           0
American avocet                              0
...                                        ...
Yellow-headed blackbird                      0
Yellow-rumped warbler                        0
Yellow-throated warbler                      0
Zebra dove                                   0
Zenaida dove                                 0

                                 ALEXANDER FIELD SOUTH WOOD COUNTY ARPT  \
Acadian flycatcher                                                    0
Alder flycatcher                                                      0
Alder/willow flycatcher complex                                       0
American alligator                                                    0
American avocet                                                       0
...                                                                 ...
Yellow-headed blackbird                                               0
Yellow-rumped warbler                                                 0
Yellow-throated warbler                                               0
Zebra dove                                                            0
Zenaida dove                                                          0

                                 ALEXANDRIA INTL  ALLEGHENY COUNTY ARPT  \
Acadian flycatcher                             0                      0
Alder flycatcher                               0                      0
Alder/willow flycatcher complex                0                      0
American alligator                             0                      0
American avocet                                0                      0
...                                          ...                    ...
Yellow-headed blackbird                        0                      0
Yellow-rumped warbler                          0                      0
Yellow-throated warbler                        0                      0
Zebra dove                                     0                      0
Zenaida dove                                   0                      0

                                 ALLEGHENY GEN HOSP EMERG HELIPORT  \
Acadian flycatcher                                               0
Alder flycatcher                                                 0
Alder/willow flycatcher complex                                  0
American alligator                                               0
American avocet                                                  0
...                                                            ...
Yellow-headed blackbird                                          0
Yellow-rumped warbler                                            0
Yellow-throated warbler                                          0
Zebra dove                                                       0
Zenaida dove                                                     0

                                 ALLEN C PERKINSON AIRPORT/BLACKSTONE ARMY AIRFIELD  \
Acadian flycatcher                                                               0
Alder flycatcher                                                                 0
Alder/willow flycatcher complex                                                  0
American alligator                                                               0
American avocet                                                                  0
...                                                                            ...
Yellow-headed blackbird                                                          0
Yellow-rumped warbler                                                            0
Yellow-throated warbler                                                          0
Zebra dove                                                                       0
Zenaida dove                                                                     0

                                 ALLENTOWN QUEEN CITY MUNICIPAL  \
Acadian flycatcher                                            0
Alder flycatcher                                              0
Alder/willow flycatcher complex                               0
American alligator                                            0
American avocet                                               0
...                                                         ...
Yellow-headed blackbird                                       0
Yellow-rumped warbler                                         0
Yellow-throated warbler                                       0
Zebra dove                                                    0
Zenaida dove                                                  0

                                 ALLIANCE MUNICIPAL ARPT  ALMATY INTL ARPT  \
Acadian flycatcher                                     0                 0
Alder flycatcher                                       0                 0
Alder/willow flycatcher complex                        0                 0
American alligator                                     0                 0
American avocet                                        0                 0
...                                                  ...               ...
Yellow-headed blackbird                                0                 0